### PR TITLE
Typo

### PR DESCRIPTION
**Pull request by PallHaraldsson**
The tagline: "differential DSL that can run fater than light and go back to the past." also has a typo, assuming "faster", but not sure how to fix.

Not sure if hyphen is wanted; also for pre- and post-condition. Auto-diff?

I look forward to looking more into this intriguing package.

### CODE REVIEW

**Comment by PallHaraldsson** [comment]
"Arbituary high order gradint (in progress)."

I missed there: "Arbitrary", and "higher-order"? Or high? Not sure what "gradint" is, "gradient"?

**Comment by GiggleLiu** [comment]
Thanks for corrections! I will be happy to merge it.
Also, thanks for your interest, I am preparing a paper about this project and is going to write more documentations to this project.

On the otherside, this project is in very early stage. It does not has blas support yet, not sure it can provide productivity in practical cases.

**Comment by GiggleLiu** [comment]
Now the documentations are added.

**Comment by GiggleLiu** [comment]
Also see this paper in preparation.
https://github.com/GiggleLiu/nilangpaper

**Pull request merged**
